#!/bin/bash
KLIPPER=~/klipper
message() {
	echo
	echo ===== "$@" =====
	echo
}
maybe() {
	if test $dryrun; then
		message '[DRYRUN]' "$@"
	else
		"$@"
	fi
}
set -eu
cd $(dirname $0)
buildonly=
dryrun=
while test $# -gt 0; do
	case "$1" in
		-b|--build) buildonly=1;;
		-d|--dry) dryrun=1;;
		*)
			message "ERROR: Unknown command line option $1"
			exit 1
			;;
	esac
	shift
done
for conf in config.*; do
	varname=${conf#config.}
	message Building variant $varname
	cat $conf > exp_$conf
	make -C $KLIPPER KCONFIG_CONFIG:=$PWD/exp_$conf OUT:=$PWD/out.$varname/ olddefconfig
	make -C $KLIPPER KCONFIG_CONFIG:=$PWD/exp_$conf OUT:=$PWD/out.$varname/ clean
	make -C $KLIPPER KCONFIG_CONFIG:=$PWD/exp_$conf OUT:=$PWD/out.$varname/ -j $(nproc)
done
if test $buildonly; then
	message Building completed, flashing skipped.
	exit 1
fi
maybe sudo systemctl stop klipper
for dev in /dev/serial/by-id/usb-Klipper_*; do
	devbase=${dev##*/}
	devname=${devbase#usb-Klipper_}
	chipname=${devname%_*}
	for varname in $chipname $devname $devbase NOT-FOUND; do
		if test "$varname" = NOT-FOUND; then
			message "ERROR: No suitable configuration found for $dev"
			exit 1
		fi
		test -r config.$varname || continue
		break
	done
	message Flashing variant $varname to $dev
	maybe make -C $KLIPPER KCONFIG_CONFIG:=$PWD/exp_config.$varname OUT:=$PWD/out.$varname/ flash FLASH_DEVICE=$dev
done
maybe sudo systemctl start klipper
message All devices flashed
